---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
- name: Install collection community.network
  community.general.ansible_galaxy_install:
    type: collection
    name: community.docker

  roles:
  - bootstrap
  - { role: docker-prep, tags: ['docker'] }
  - { role: ansible-traefik, tags: ['traefik'] }