---
---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
  - name: Install community.docker collection
    community.general.galaxy_collection:
      name: community.docker
      state: present
      
  roles:
  - bootstrap
  - { role: docker-prep, tags: ['docker'] }
  - { role: ansible-traefik, tags: ['traefik'] }