---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
  - name: Install community.docker collection
    community.general.ansible_galaxy_install:
      type: collection
      name: community.docker

  roles:
  - bootstrap
  #- docker-prep
  #- ansible-traefik