---
- hosts: localhost
  connection: local
  become: true
  collections:
  - community.docker
  roles:
  - bootstrap
  - { role: docker-prep, tags: ['docker'] }
  - { role: ansible-traefik, tags: ['traefik'] }