---
  - tasks:
    - block:
      - name: Install community.docker module
        command: ansible-galaxy collection install community.docker
        ignore_errors: yes
      - include: playbook.yml  # or whatever file you want to include