---
- name: Install community.docker collection
  become: true

  tasks:
  - name: Install community.docker collection
    ansible.builtin.ansible_galaxy:
      name: community.docker
      source: galaxy