---
- name: Install community.docker collection
  become: true

  tasks:
- name: Install collection community.network
  community.general.ansible_galaxy_install:
    type: collection
    name: community.docker