- name: Run docker-compose with env file
  community.docker.docker_compose_v2:
    project_name: udm
    project_src: '{{ playbook_dir }}/files'
    file: docker-compose-udms.yml
    env_file: '{{ playbook_dir }}/files/env'